drop table if exists gcp_ga.`Order`;
create table if not exists gcp_ga.`Order`
(
    inserted_at             TIMESTAMP,
    event_date              INT64,
    event_timestamp         TIMESTAMP,
    user_pseudo_id          STRING,
    country                 STRING,
    city                    STRING,
    id                      STRING,
    version                 STRING,
    install_store           STRING,
    install_source          STRING,
    platform                STRING,
    name                    STRING,
    hostname                STRING,
    total_item_quantity     INT64,
    purchase_revenue_in_usd FLOAT64,
    purchase_revenue        FLOAT64,
    shipping_value_in_usd   FLOAT64,
    shipping_value          FLOAT64,
    tax_value_in_usd        FLOAT64,
    tax_value               FLOAT64,
    unique_items            INT64,
    transaction_id          STRING,
    engaged_session_event   STRING,
    firebase_event_origin   STRING,
    firebase_screen_class   STRING,
    ga_session_id           STRING,
    ga_session_number       STRING,
    item_count              STRING,
    order_id                STRING,
    order_total             STRING
)
    partition by DATE_TRUNC(event_timestamp, MONTH)
    cluster by order_id, user_pseudo_id, ga_session_id
    options (require_partition_filter = TRUE);

drop table if exists gcp_ga.add_to_cart;
create table if not exists gcp_ga.add_to_cart
(
    inserted_at           TIMESTAMP,
    event_date            INT64,
    event_timestamp       TIMESTAMP,
    user_pseudo_id        STRING,
    country               STRING,
    city                  STRING,
    id                    STRING,
    version               STRING,
    install_store         STRING,
    install_source        STRING,
    platform              STRING,
    name                  STRING,
    hostname              STRING,
    app_version           STRING,
    campaign              STRING,
    campaign_id           STRING,
    cart_id               STRING,
    content               STRING,
    currency              STRING,
    engaged_session_event STRING,
    event_platform        STRING,
    firebase_conversion   STRING,
    firebase_event_origin STRING,
    firebase_screen_class STRING,
    first_name            STRING,
    ga_session_id         STRING,
    ga_session_number     STRING,
    gclid                 STRING,
    ignore_referrer       STRING,
    last_name             STRING,
    page_location         STRING,
    page_referrer         STRING,
    phone_number          STRING,
    quantity              STRING,
    selected_currency     STRING,
    seller                STRING
)
    partition by DATE_TRUNC(event_timestamp, MONTH)
    cluster by country, city, user_pseudo_id, ga_session_id
    options (require_partition_filter = TRUE);

drop table if exists gcp_ga.begin_checkout;
create table if not exists gcp_ga.begin_checkout
(
    inserted_at              TIMESTAMP,
    event_date               INT64,
    event_timestamp          TIMESTAMP,
    user_pseudo_id           STRING,
    category                 STRING,
    mobile_brand_name        STRING,
    mobile_model_name        STRING,
    mobile_marketing_name    STRING,
    mobile_os_hardware_model STRING,
    operating_system         STRING,
    operating_system_version STRING,
    vendor_id                STRING,
    advertising_id           STRING,
    language                 STRING,
    is_limited_ad_tracking   STRING,
    time_zone_offset_seconds INT64,
    browser                  STRING,
    browser_version          STRING,
    country                  STRING,
    city                     STRING,
    id                       STRING,
    version                  STRING,
    install_store            STRING,
    install_source           STRING,
    platform                 STRING,
    name                     STRING,
    hostname                 STRING,
    item_id                  STRING,
    item_brand               STRING,
    item_variant             STRING,
    price_in_usd             FLOAT64,
    price                    FLOAT64,
    quantity                 INT64,
    coupon                   STRING,
    affiliation              STRING,
    promotion_id             STRING,
    promotion_name           STRING,
    creative_slot            STRING,
    app_version              STRING,
    cart_id                  STRING,
    currency                 STRING,
    engaged_session_event    STRING,
    event_platform           STRING,
    firebase_conversion      STRING,
    firebase_event_origin    STRING,
    firebase_screen_class    STRING,
    first_name               STRING,
    ga_session_id            STRING,
    ga_session_number        STRING,
    last_name                STRING,
    phone_number             STRING,
    selected_currency        STRING
)
    partition by DATE_TRUNC(event_timestamp, MONTH)
    cluster by country, city, user_pseudo_id, ga_session_id
    options (require_partition_filter = TRUE);

drop table if exists gcp_ga.page_view;
create table if not exists gcp_ga.page_view
(
    inserted_at           TIMESTAMP,
    event_date            INT64,
    event_timestamp       TIMESTAMP,
    user_pseudo_id        STRING,
    country               STRING,
    city                  STRING,
    id                    STRING,
    version               STRING,
    install_store         STRING,
    install_source        STRING,
    platform              STRING,
    name                  STRING,
    hostname              STRING,
    campaign              STRING,
    campaign_id           STRING,
    content               STRING,
    engaged_session_event STRING,
    ga_session_id         STRING,
    ga_session_number     STRING,
    gclid                 STRING,
    ignore_referrer       STRING,
    page_location         STRING,
    page_referrer         STRING
)
    partition by DATE_TRUNC(event_timestamp, MONTH)
    cluster by country, city, user_pseudo_id, ga_session_id
    options (require_partition_filter = TRUE);

drop table if exists gcp_ga.purchase;
create table if not exists gcp_ga.purchase
(
    inserted_at              TIMESTAMP,
    event_date               INT64,
    event_timestamp          TIMESTAMP,
    user_pseudo_id           STRING,
    category                 STRING,
    mobile_brand_name        STRING,
    mobile_model_name        STRING,
    mobile_marketing_name    STRING,
    mobile_os_hardware_model STRING,
    operating_system         STRING,
    operating_system_version STRING,
    vendor_id                STRING,
    advertising_id           STRING,
    language                 STRING,
    is_limited_ad_tracking   STRING,
    time_zone_offset_seconds INT64,
    browser                  STRING,
    browser_version          STRING,
    country                  STRING,
    city                     STRING,
    id                       STRING,
    version                  STRING,
    install_store            STRING,
    install_source           STRING,
    platform                 STRING,
    name                     STRING,
    hostname                 STRING,
    item_id                  STRING,
    item_brand               STRING,
    item_variant             STRING,
    price_in_usd             FLOAT64,
    price                    FLOAT64,
    quantity                 INT64,
    coupon                   STRING,
    affiliation              STRING,
    promotion_id             STRING,
    promotion_name           STRING,
    creative_slot            STRING,
    app_version              STRING,
    cart_id                  STRING,
    currency                 STRING,
    engaged_session_event    STRING,
    event_platform           STRING,
    firebase_conversion      STRING,
    firebase_event_origin    STRING,
    firebase_screen_class    STRING,
    first_name               STRING,
    ga_session_id            STRING,
    ga_session_number        STRING,
    ignore_referrer          STRING,
    last_name                STRING,
    page_location            STRING,
    page_referrer            STRING,
    payment_type             STRING,
    phone_number             STRING,
    shipping                 STRING,
    shipping_city            STRING,
    shipping_state           STRING,
    shipping_tier            STRING,
    transaction_id           STRING
)
    partition by DATE_TRUNC(event_timestamp, MONTH)
    cluster by user_pseudo_id, ga_session_id, item_brand, item_variant
    options (require_partition_filter = TRUE);

drop table if exists gcp_ga.remove_from_cart;
create table if not exists gcp_ga.remove_from_cart
(
    inserted_at           TIMESTAMP,
    event_date            INT64,
    event_timestamp       TIMESTAMP,
    user_pseudo_id        STRING,
    country               STRING,
    city                  STRING,
    id                    STRING,
    version               STRING,
    install_store         STRING,
    install_source        STRING,
    platform              STRING,
    name                  STRING,
    hostname              STRING,
    app_version           STRING,
    campaign              STRING,
    campaign_id           STRING,
    cart_id               STRING,
    content               STRING,
    currency              STRING,
    engaged_session_event STRING,
    event_platform        STRING,
    firebase_event_origin STRING,
    firebase_screen_class STRING,
    first_name            STRING,
    ga_session_id         STRING,
    ga_session_number     STRING,
    gclid                 STRING,
    ignore_referrer       STRING,
    last_name             STRING,
    page_location         STRING,
    page_referrer         STRING,
    phone_number          STRING,
    selected_currency     STRING
)
partition by DATE_TRUNC(event_timestamp, MONTH)
    cluster by country, city, user_pseudo_id, ga_session_id
    options (require_partition_filter = TRUE);

drop table if exists gcp_ga.select_item;
create table if not exists gcp_ga.select_item
(
    inserted_at              TIMESTAMP,
    event_date               INT64,
    event_timestamp          TIMESTAMP,
    user_pseudo_id           STRING,
    category                 STRING,
    mobile_brand_name        STRING,
    mobile_model_name        STRING,
    mobile_marketing_name    STRING,
    mobile_os_hardware_model STRING,
    operating_system         STRING,
    operating_system_version STRING,
    vendor_id                STRING,
    advertising_id           STRING,
    language                 STRING,
    is_limited_ad_tracking   STRING,
    time_zone_offset_seconds INT64,
    browser                  STRING,
    browser_version          STRING,
    country                  STRING,
    city                     STRING,
    id                       STRING,
    version                  STRING,
    install_store            STRING,
    install_source           STRING,
    platform                 STRING,
    name                     STRING,
    hostname                 STRING,
    item_id                  STRING,
    item_brand               STRING,
    item_variant             STRING,
    price_in_usd             FLOAT64,
    price                    FLOAT64,
    quantity                 INT64,
    coupon                   STRING,
    affiliation              STRING,
    promotion_id             STRING,
    promotion_name           STRING,
    creative_slot            STRING,
    app_version              STRING,
    component_display_mode   STRING,
    component_id             STRING,
    component_name           STRING,
    component_type           STRING,
    currency                 STRING,
    engaged_session_event    STRING,
    event_platform           STRING,
    firebase_error           STRING,
    firebase_event_origin    STRING,
    firebase_screen_class    STRING,
    first_name               STRING,
    ga_session_id            STRING,
    ga_session_number        STRING,
    item_list_id             STRING,
    item_list_name           STRING,
    last_name                STRING,
    location_id              STRING,
    phone_number             STRING,
    selected_currency        STRING,
    selected_language        STRING
)
    partition by DATE_TRUNC(event_timestamp, MONTH)
    cluster by user_pseudo_id, ga_session_id, item_brand, item_variant
    options (require_partition_filter = TRUE);

drop table if exists gcp_ga.select_promotion;
create table if not exists gcp_ga.select_promotion
(
    inserted_at              TIMESTAMP,
    event_date               INT64,
    event_timestamp          TIMESTAMP,
    user_pseudo_id           STRING,
    category                 STRING,
    mobile_brand_name        STRING,
    mobile_model_name        STRING,
    mobile_marketing_name    STRING,
    mobile_os_hardware_model STRING,
    operating_system         STRING,
    operating_system_version STRING,
    vendor_id                STRING,
    advertising_id           STRING,
    language                 STRING,
    is_limited_ad_tracking   STRING,
    time_zone_offset_seconds INT64,
    browser                  STRING,
    browser_version          STRING,
    country                  STRING,
    city                     STRING,
    id                       STRING,
    version                  STRING,
    install_store            STRING,
    install_source           STRING,
    platform                 STRING,
    name                     STRING,
    hostname                 STRING,
    item_id                  STRING,
    item_brand               STRING,
    item_variant             STRING,
    price_in_usd             FLOAT64,
    price                    FLOAT64,
    quantity                 INT64,
    coupon                   STRING,
    affiliation              STRING,
    promotion_id             STRING,
    promotion_name           STRING,
    creative_slot            STRING,
    app_version              STRING,
    campaign                 STRING,
    component_display_mode   STRING,
    component_id             STRING,
    component_type           STRING,
    content                  STRING,
    creative_ranking         STRING,
    destination_id           STRING,
    destination_type         STRING,
    engaged_session_event    STRING,
    event_platform           STRING,
    firebase_event_origin    STRING,
    firebase_screen_class    STRING,
    first_name               STRING,
    ga_session_id            STRING,
    ga_session_number        STRING,
    gclid                    STRING,
    ignore_referrer          STRING,
    item_list_id             STRING,
    item_list_name           STRING,
    last_name                STRING,
    location_id              STRING,
    page_location            STRING,
    page_referrer            STRING,
    phone_number             STRING,
    promotion_location_id    STRING,
    selected_currency        STRING,
    selected_language        STRING
)
    partition by DATE_TRUNC(event_timestamp, MONTH)
    cluster by country, city, user_pseudo_id, ga_session_id
    options (require_partition_filter = TRUE);

drop table if exists gcp_ga.session_start;
create table if not exists gcp_ga.session_start
(
    inserted_at              TIMESTAMP,
    event_date               INT64,
    event_timestamp          TIMESTAMP,
    user_pseudo_id           STRING,
    category                 STRING,
    mobile_brand_name        STRING,
    mobile_model_name        STRING,
    mobile_marketing_name    STRING,
    mobile_os_hardware_model STRING,
    operating_system         STRING,
    operating_system_version STRING,
    vendor_id                STRING,
    advertising_id           STRING,
    language                 STRING,
    is_limited_ad_tracking   STRING,
    time_zone_offset_seconds INT64,
    browser                  STRING,
    browser_version          STRING,
    country                  STRING,
    city                     STRING,
    id                       STRING,
    version                  STRING,
    install_store            STRING,
    install_source           STRING,
    platform                 STRING,
    name                     STRING,
    hostname                 STRING,
    debug_event              STRING,
    engaged_session_event    STRING,
    firebase_conversion      STRING,
    firebase_event_origin    STRING,
    firebase_screen_class    STRING,
    ga_session_id            STRING,
    ga_session_number        STRING,
    ignore_referrer          STRING,
    page_location            STRING,
    page_referrer            STRING
)
    partition by DATE_TRUNC(event_timestamp, MONTH)
    cluster by country, city, user_pseudo_id, ga_session_id
    options (require_partition_filter = TRUE);

drop table if exists gcp_ga.view_item;
create table if not exists gcp_ga.view_item
(
    inserted_at              TIMESTAMP,
    event_date               INT64,
    event_timestamp          TIMESTAMP,
    user_pseudo_id           STRING,
    category                 STRING,
    mobile_brand_name        STRING,
    mobile_model_name        STRING,
    mobile_marketing_name    STRING,
    mobile_os_hardware_model STRING,
    operating_system         STRING,
    operating_system_version STRING,
    vendor_id                STRING,
    advertising_id           STRING,
    language                 STRING,
    is_limited_ad_tracking   STRING,
    time_zone_offset_seconds INT64,
    browser                  STRING,
    browser_version          STRING,
    country                  STRING,
    city                     STRING,
    id                       STRING,
    version                  STRING,
    install_store            STRING,
    install_source           STRING,
    platform                 STRING,
    name                     STRING,
    hostname                 STRING,
    item_id                  STRING,
    item_brand               STRING,
    item_variant             STRING,
    price_in_usd             FLOAT64,
    price                    FLOAT64,
    quantity                 INT64,
    coupon                   STRING,
    affiliation              STRING,
    promotion_id             STRING,
    promotion_name           STRING,
    creative_slot            STRING,
    app_version              STRING,
    campaign                 STRING,
    campaign_id              STRING,
    content                  STRING,
    currency                 STRING,
    engaged_session_event    STRING,
    event_platform           STRING,
    firebase_conversion      STRING,
    firebase_event_origin    STRING,
    firebase_screen_class    STRING,
    first_name               STRING,
    ga_session_id            STRING,
    ga_session_number        STRING,
    ignore_referrer          STRING,
    last_name                STRING,
    page_location            STRING,
    page_referrer            STRING,
    phone_number             STRING,
    seller                   STRING
)
    partition by DATE_TRUNC(event_timestamp, MONTH)
    cluster by user_pseudo_id, ga_session_id, item_brand, item_variant
    options (require_partition_filter = TRUE);

